# Generated by Django 5.2.7 on 2025-10-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultamedica',
            name='estado',
            field=models.CharField(choices=[('AGENDADA', 'Agendada'), ('EN_CURSO', 'En Curso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('NO_ASISTIO', 'No Asistió')], default='AGENDADA', max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tipo_sangre',
            field=models.CharField(choices=[('A+', 'A positivo'), ('A-', 'A negativo'), ('B+', 'B positivo'), ('B-', 'B negativo'), ('AB+', 'AB positivo'), ('AB-', 'AB negativo'), ('O+', 'O positivo'), ('O-', 'O negativo')], default='O+', max_length=3),
        ),
        migrations.AlterField(
            model_name='recetamedica',
            name='frecuencia',
            field=models.CharField(choices=[('8H', 'Cada 8 horas'), ('12H', 'Cada 12 horas'), ('24H', 'Cada 24 horas'), ('48H', 'Cada 48 horas'), ('SEMANAL', 'Una vez por semana'), ('UNICA', 'Dosis única')], default='24H', max_length=10),
        ),
    ]
