# Generated by Django 5.2.7 on 2025-10-15 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0002_alter_consultamedica_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('tipo_cita', models.CharField(choices=[('PRIMERA_VEZ', 'Primera vez'), ('CONTROL', 'Control'), ('URGENCIA', 'Urgencia'), ('SEGUIMIENTO', 'Seguimiento')], default='PRIMERA_VEZ', max_length=20)),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('REALIZADA', 'Realizada'), ('NO_ASISTIO', 'No asistió')], default='PROGRAMADA', max_length=20)),
                ('motivo', models.CharField(max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('duracion_minutos', models.IntegerField(default=30)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_clinica.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_clinica.paciente')),
            ],
        ),
    ]
